### ISSUE TITLE
Guided busways don't render

### ISSUE THREAD

**Issue by sbdavis** [dschwen/wikiminiatlas#12]
Ways with Tag:highway=bus_guideway do not appear to render in WikiMiniAtlas.

For example, compare the miniatlas view at https://en.wikipedia.org/wiki/O-Bahn_Busway with https://www.openstreetmap.org/?mlat=-34.905556&mlon=138.612778&zoom=15#map=15/-34.9056/138.6128 - the busway is missing from the map on the article about it!

**Comment by dschwen** [comment]
Well... you lean something new everyday! :-)
Thanks for pointing that out. The change is live now (you may need to purge your browser cache).
