### ISSUE TITLE
WIWOSM

### ISSUE THREAD

**Issue by sbdavis** [dschwen/wikiminiatlas#13]
Is this the place to raise the concern that WIWOSM does not seem to have updated for months? 

I have entered new wikipedia and wikipedia:en tags into OSM on some rivers and highways, but they do not seem to be getting to WikiMiniAtlas, whereas ones that have been there for longer render in the miniatlas on the corresponding Wikipedia articles.

**Comment by dschwen** [comment]
I'm just a data user of wiwosm, but I'll pass this on.

**Comment by sbdavis** [comment]
Thank you. I haven't found the right place to find out if it is still maintained by anyone.

**Comment by kolossos** [comment]
WIWOSM was updated last week after a long break. I hope everthing is correct now and that daily updates running fine in the future.

**Comment by sbdavis** [comment]
Thank you kolossos. I need to be more specific. [[Gawler River]] and [[Wakefield River]] both show a nice route in the WikiMinAtlas. [[Light River (South Australia)]] and [[Tod Highway]] do not, and I haven't worked out the difference that matters. Perhaps I need to find or write/improve a tutorial once I understand it myself.

**Comment by kolossos** [comment]
I checked the Light River in Australia. This river need an Wikipedia-tag in OpenStreetMap. This is missing so it's no bug from our side. 
See: http://wiki.openstreetmap.org/wiki/WIWOSM
