### ISSUE TITLE
GeoHack map for all Wikipedia coordinates recognises Islamic State as a country, not Syria

### ISSUE THREAD

**Issue by bluedinogeography** [dschwen/wikiminiatlas#14]
![syria not isil](https://cloud.githubusercontent.com/assets/16004780/11377318/86f5a7fe-92e5-11e5-85eb-44340c165bea.jpg)

**Comment by dschwen** [comment]
Oh sh@#! Well, this is not an endorsement. WMA uses a metric based on article size and coordinate type. I'll investigate...

**Comment by bluedinogeography** [comment]
Thanks!

**Comment by dschwen** [comment]
Dang it. I see the entry in the database, but I don't see where on Wikipedia this information is located. The ISIL/Daesh article linked on the WMA does not seem to have a coordinate template. Where is this coming from. Do you see it? The best approach would be to fix this on Wikipedia (i.e. remove the `type=country` flag on the coordinates, as this is not a recognized country!).
The WikiMiniAtlas only reflects what is put on Wikipedia, I'm not making any editorial decisions here.

**Comment by bluedinogeography** [comment]
Unfortunately, no I don't. Initially we (a friend and I, after I posted this on Facebook 2 months ago) contacted Wikipedia. They are the ones that told us they don't oversee the maps, rather it's a group of volunteers and, in particular, you who is the best person to contact. I made this account specifically so I could contact you and try solve this issue, but I'm not at all experienced with editing Wikipedia or WikiMiniAtlas. So how exactly does WikiMiniAtlas work? Does it take the mean or median country label of all the articles with coordinates in Syria?

**Comment by dschwen** [comment]
All the labels displayed on the map correspond to tags added to Wikipedia
articles. If some coordinate tag is set as a "country" on wikipedia it is
set bold on the WMA. I will investigate this further, however I've been on
travel abroad and will be until the end of the week. So sorry about the
slow replies. I could add a manual override for ISIL but I'd have to do so
for every language (there are over 50 I support!) and if have to repeat
this for every future problem. So of course I'd prefer if this gets fixed
at the source, which is the Wikipedia article containing the coordinates.

**Comment by dschwen** [comment]
Ok, that label is gone now after I refreshed the label database last night. It seems the database replication on labs was stuck. I could not find those coordinates on the wiki for the life of me. They had probably been removed already, but the database was lagging. Thanks for reporting this.

**Comment by bluedinogeography** [comment]
Thank you!!!
