### ISSUE TITLE
The scale is not displayed

### ISSUE THREAD

**Issue by krischan111** [dschwen/wikiminiatlas#15]
Currently the wikiminiatlas does not show the scale. I tried it with current versions of firefox, ie and chrome. Happens in de wp and en wp. Instead of the scale, a white bar is displayed with the label NaN.

![wikiminiatlasnan](https://cloud.githubusercontent.com/assets/16327708/11854830/c42994ce-a446-11e5-8755-60ed1e92e779.png)

**Comment by dschwen** [comment]
Thanks for the report. I'll investigate!

**Comment by dschwen** [comment]
Ok, that was a tiny typo. Fixed in 8cc7ff3. Thanks again!

**Comment by krischan111** [comment]
That was fast, thanks dschwen!
