### ISSUE TITLE
Zoom issue on Zanzibar

### ISSUE THREAD

**Issue by batje** [dschwen/wikiminiatlas#16]
I am editing pages on Zanzibar and I have the feeling there is some smartness in the software preventing a high initial zoom level.
For example on https://en.wikipedia.org/wiki/House_of_Wonders you can clearly see, that the scale:500 that I set, is used, and then _flash_ the map zooms out again.
Manually zooming back in works.

When I use the same zoom level in Greece, I do not have this issue. See https://en.wikipedia.org/wiki/Temple_of_Artemis

Is this fixable? How?

**Comment by batje** [comment]
BTW, the functionality to pull OpenStreetMap relations works really nicely. Thanks for that. Here is a sample from our project: https://en.wikipedia.org/wiki/Michenzani

**Comment by dschwen** [comment]
Yeah, I see the issue. What happens is that the WMA uses to the extents of the OSM relation if it exists. Is there any reason to zoom in that tight on the Zanzibar as the initial viewport?

**Comment by dschwen** [comment]
By the way, you can manually refresh the map (for the current viewport) with new data from OpenStreetMap by pressing `p` while the WMA is in focus. I did that a couple of times and saw a **ton** of building data appear for that _Stone Town_ area.

**Comment by batje** [comment]
We did aprx.8000 building outlines, 4500 with a lot of detail in the area and using the info for urban planning.
Interesting you mention WMA zooms into the relation. Most buildings in Stone Town (like Tippu Tip's house) are not a relation but a way. So what is WMA zooming *out* to, after receiving my very strict command to zoom in closely? Should I turn the building into a relation? Or should WMA support OSM ways (and nodes) with wikipedia keys?
I would like to zoom in closer, because the pages for the buildings are already categorized as 'Buildings in Zanzibar' and it is already pretty clear the house is in Stone Town from the page. I would like (to be able) to use the map to give a more local context.

(On the Michengani page, WMA shows an OSM relation, but I dont think it found the ideal zoomlevel, i would expect that to me slightly higher imho).

**Comment by batje** [comment]
BTW, this page uses type=landmark and the zoomlevel is even lower
https://en.wikipedia.org/wiki/Amaan_Stadium

That is not how to show a stadium :-)

**Comment by dschwen** [comment]
@batje, sorry I may not be on the same page here. Could you tell me which coordinate in which article is giving unexpected behavior? Way or relation should not matter.

**Comment by batje** [comment]
The House of Wonders & Amaan Stadium are too zoomed out.
The Temple of Artemis is correct (and the exact same as House of Wonders).

**Comment by dschwen** [comment]
Ok, I made an edit in https://en.wikipedia.org/wiki/Amaan_Stadium to show you how to select the zoom level. Use `dim:200` (object dimensions 200m) to customize the zoom.

**Comment by batje** [comment]
Wonderful.
Now why does that exact same configuration not work for the house of wonders?
https://en.wikipedia.org/wiki/House_of_Wonders

**Comment by dschwen** [comment]
Looks like this is not an issue anymore
