### ISSUE TITLE
old coastline data

### ISSUE THREAD

**Issue by Locke** [dschwen/wikiminiatlas#19]
It appears to me that the coastline data has been imported a log time ago and has not been updated since.

I just looked around [Macuse](https://en.wikipedia.org/wiki/Macuse). In the WikiMiniAtlas you can see much more water than on OpenStreetMap.

Example: In OSM the [way 20156703](https://www.openstreetmap.org/way/20156703) was part of the coastline only until two years ago when the coastline in that region was restructured. However you can still see its shape in WikiMiniAtlas as water. This leads to strange rendering east of that way on the residential area, where untagged areas are rendered as water.

**Comment by dschwen** [comment]
Thanks @Locke, looks like I need to Reimport that data.

**Comment by dschwen** [comment]
Sorry for the delay. It took me a while to get to the bottom of this. Setting the wheels in motion now.

**Comment by dschwen** [comment]
This should be resolved now. See https://phabricator.wikimedia.org/T140296.

**Comment by dschwen** [comment]
This might need a tile cache purge

**Comment by Locke** [comment]
As some time has passed I just looked at the map again. The tile cache purge hasn't happend yet, or is there an additional issue?

On higher zoom levels it looks good:

![screenshot from 2017-04-03 11 28 33_](https://cloud.githubusercontent.com/assets/53905/24603404/eff5572a-1860-11e7-9cb1-d89e87978ac0.png)

https://wma.wmflabs.org/iframe.html?-17.706944444444442_37.18944444444444_0_0_en_13_en_-17.694396972656257_37.28593826293945&globe=Earth&page=Macuse&lang=en

But not on lower ones:

![screenshot from 2017-04-03 11 28 23_](https://cloud.githubusercontent.com/assets/53905/24603408/f9c7e02e-1860-11e7-9dde-44fb42787728.png)

https://wma.wmflabs.org/iframe.html?-17.706944444444442_37.18944444444444_0_0_en_12_en_-17.694396972656257_37.28588104248047&globe=Earth&page=Macuse&lang=en

I noticed that a lot of newer roads are not displayed on the lower zoom level, and also that the residential areas are not rendered. Is this expected on that zoom level or are the tiles just outdated?

**Comment by dschwen** [comment]
I'll trigger that today

**Comment by dschwen** [comment]
The purge is running. I'm deleting pre-rendered tiles older than 90 days. Expect this to take at least a full day. A week ago I purged the client-side rendered JSON data, which is what updated the higher resolutions.

**Comment by dschwen** [comment]
Gulp, I noticed that on-demand tile rendering was broken, so deleting the old pre-rendered tiles left the map in a desolate state. This is fixed now and the purge (which I halted temporarily while fixing that issue) is currently somewhere in zoomlevel 11

**Comment by dschwen** [comment]
Now in Zoomlevel 12. Your link is already partially refreshed and showing the new coastline.

**Comment by Locke** [comment]
Tanks for all the effort so far! :smiley: 

On zoom level 12 the new data is rendered (landuse, roads and wetland), but it looks like the underlying layer is still based on the old coastline data from before the its reimport. I think that this base layer with the coastline needs to be rerendered as well.

![screenshot from 2017-04-04 21 58 54__](https://cloud.githubusercontent.com/assets/53905/24676373/0685b318-1983-11e7-81b2-9929f0c5dcdb.png)

**Comment by dschwen** [comment]
Hmm, yeah, there is a discrepancy, indeed. I will investigate this.

**Comment by dschwen** [comment]
Ugh, this is still an issue. Even after revamping the rendering system and adding my own (up to date) OSM database mirror. The lower resolution tiles don't get their coastline data from the database. The high zoom tiles do, and I updated the coastline in the DB. I'll try updating the SHP coastline files for the lower zoom.

**Comment by dschwen** [comment]
![image](https://user-images.githubusercontent.com/202302/198153163-ae9b768f-1934-4b6b-b304-ad66a39d5dd9.png)

Fixed!

**Comment by dschwen** [comment]
I'll have to gradually purge the tile cache. I manually cleared it in this area.
