### ISSUE TITLE
Wikimedia tile service

### ISSUE THREAD

**Issue by ckoerner** [dschwen/wikiminiatlas#25]
Half a feature request and half a general request for more information. Would it be possible to use the Wikimedia tile service in WikiMiniAtlas? I'm curious (as a volunteer) if the service is able to be used, and if not, why. I can help provide more information but I'll start by leaving a link. :)

https://www.mediawiki.org/wiki/Maps#Production_maps_cluster

**Comment by dschwen** [comment]
Yeah, this has been discussed **many** times :-). WikiMiniAtlas is a lot more than a script to show a slippy map. There is a lot of added value code (overlays, 3D building rendering, clickable text labels, other celestial bodies i.e. the moon(s) and planets. etc.)

* The plate carree projection is at the core of all this stuff. This is hard to change to web Mercator. 
* The prerendered tiles were cluttered with text (I understand now text-free tiles are available though)
* No tile service for the earth moon, titan, Io, Mars, Venus, Mercury
* No tile service for physical maps, landsat images, etc.

**Comment by ckoerner** [comment]
I had figured I wasn't the first to bring it up. :) I thought I'd ask and appreciate you taking the time to help me understand why!
