### ISSUE TITLE
jQuery.fn.hover() is deprecated

### ISSUE THREAD

**Issue by he7d3r** [dschwen/wikiminiatlas#26]
The script still uses hover (here: [1](https://github.com/dschwen/wikiminiatlas/blob/4a6fd1c09d40530888d244224b7d95530bf5018f/wikiminiatlas.js#L470), [2](https://github.com/dschwen/wikiminiatlas/blob/4a6fd1c09d40530888d244224b7d95530bf5018f/wikiminiatlas.js#L513)) which causes the warning
> JQMIGRATE: jQuery.fn.hover() is deprecated

when it is loaded on Wikipedia.

**Comment by samwilson** [comment]
This has been fixed on-wiki for ages, and #33 brings the change to this repo.

**Comment by he7d3r** [comment]
Fixed by https://github.com/dschwen/wikiminiatlas/pull/33
