### ISSUE TITLE
wma.wmflabs.org: 502 Bad Gateway

### ISSUE THREAD

**Issue by nicolas-raoul** [dschwen/wikiminiatlas#28]
How to reproduce:
- Go to https://commons.wikimedia.org/wiki/File:Shropshire_Union_Canal_at_Wheaton_Aston,_Staffordshire_-_geograph.org.uk_-_1375583.jpg
- Click on the small globe near "Camera location"
- The popup says "502 Bad Gateway nginx"

URL is https://wma.wmflabs.org/iframe.html?wma=52.714999_-2.216675_600_400_commons_19.931568569324178_en&globe=Earth&lang=commons&page=&awt=0

Also reported at https://phabricator.wikimedia.org/T185798

**Comment by dschwen** [comment]
This has long been fixed
