### ISSUE TITLE
trees/forest rendering

### ISSUE THREAD

**Issue by basxto** [dschwen/wikiminiatlas#41]
It looks like `natural=wood` works fine, but `landuse=forest` gets ignored for rendering. Forests used for forestry get tagged like this.
In Germany, where the majority of forests get used that way, that basically leads to deforestation.

**Comment by dschwen** [comment]
This is being addressed here: https://github.com/dschwen/wikiminiatlas_servers/commit/40bc178cb67d39824fe8b5392e0e011903fc112e

**Comment by dschwen** [comment]
Ok, I'm hitting a little snag here because of how `landuse` is stored in the DB....

**Comment by dschwen** [comment]
Ok, here's an old tile:
![image](https://github.com/user-attachments/assets/494951ba-9843-4e27-8545-f2fa25caf282)

and here's how it renders now:
![image](https://github.com/user-attachments/assets/bdb67e85-8b89-4258-9745-3ac9db3c787e)

**Comment by dschwen** [comment]
Yeah, this is adding a lot of new forest. I'll have to rebuild tiles over the next couple of days.

![image](https://github.com/user-attachments/assets/86f51b38-2af3-49c7-be7e-0a4b544e3a09)

**Comment by dschwen** [comment]
See https://github.com/dschwen/wikiminiatlas_servers/commit/647c80d5f6eb2a252ca6db8cdaf4c80ac1afc5d2
