### ISSUE TITLE
Replace globe icon with 'fa-globe' icon from Font Awesome

### ISSUE THREAD

**Issue by atdt** [dschwen/wikiminiatlas#5]
I recommend replacing the globe icon with the one provided by Font Awesome:

http://fortawesome.github.io/Font-Awesome/icons/

It is consistent with the look and feel of the WikiFont icon set: http://www.mediawiki.org/wiki/Design/WikiFont

**Comment by dschwen** [comment]
Sorry, too much time has passed. WikiFont itself is deprecated by now.
