### ISSUE TITLE
Miss Chinese label

### ISSUE THREAD

**Issue by Supaplextw** [dschwen/wikiminiatlas#6]
It's very nice to have WikiMiniAtlas on the coordinated articles. There's a problem when I read Chinese Wikipedia article. When I switch the  language label on the WikiMiniAtlas, I can't switch back to Chinese label. There's no Chinese option on the list. It will be more convenience to add it rather then to reload the page to bring back to the Chinese label on. 

Supaplex

**Comment by dschwen** [comment]
Yes, good point! I will work on this next.

**Comment by dschwen** [comment]
6344f6fd puts the current site language and the user interface language at the top of the label list.

I'll have to add entries to that menu for each language that I have labels for.

**Comment by dschwen** [comment]
d2cb3fc adds all supported languages to the dropdown. @Supaplextw I only have ```zh``` in there, without the various suffixes. I don't know enough about what those actually mean. Do we have automatic "transliteration" (or what is that called?) for those, or are there separate wikipedias for these language versions? Please let me know how I should support labels on those.

**Comment by Supaplextw** [comment]
There's only who Chinese Wikipedia, access through Taiwan, China, Hong Kong, and Macu. The zh stands for Chinese Wikipedia. And the zh-tw, zh-cn, zh-hant, zh-hans etc. these suffixes are for different character and terms used in Taiwan, China, Hong Kong, or Macu. There's used for the auto-convert system to decide which characters and terms to display.

**Comment by Supaplextw** [comment]
I saw the change you made on Commons. The zh-min-nan and zh-classical are separated Wiki, not belong to Chinese Wikipedia.

**Comment by dschwen** [comment]
Ok, would you say this issue is resolved, or do you have further suggestions?

**Comment by Supaplextw** [comment]
Partial I think. If the WikiMiniAtlas could display the correspond right character in Chinese depends on user prefer language sitting, it will be perfect. Maybe label this issue enhancement or rename the issue for further discussion about how to deal with the Chinese Character conversion part.

**Comment by dschwen** [comment]
OK, I'll open a new issue for Chinese character conversion.
