### ISSUE TITLE
Chinese character conversion in labels

### ISSUE THREAD

**Issue by dschwen** [dschwen/wikiminiatlas#7]
The zh labels should be provided in the various regional variants (Taiwan, Macao, etc.). On Wikipedia this is done automatically. Maybe the label server could do this on the fly. Per @supaplextw

**Comment by dschwen** [comment]
@Supaplextw, could you help me with this issue? I need a list of the language codes that the automatic character conversion should support and the name of that language. I.e.

```
{
  'zh-hk': 'Chinese (Hong Kong)',
  'zh-tw': 'Taiwanese chinese',
  ...
}
```

Or whatever those variants are commonly called (and the names should of course be in the native language :-).

**Comment by dschwen** [comment]
I guess this is what I need (```&lrm;``` is the unicode left to right mark)
```
{
 'zh': '中文',
 'zh-hans': '中文（简体）&lrm;',
 'zh-hant': '中文（繁體）&lrm;',
 'zh-cn': '中文（中国大陆）&lrm;',
 'zh-hk': '中文（香港）&lrm;',
 'zh-mo': '中文（澳門）&lrm;',
 'zh-sg': '中文（新加坡）&lrm;',
 'zh-tw': '中文（台灣）&lrm;'
}
```

Now I just need to figure out the UI for setting the variant.

**Comment by dschwen** [comment]
This should now be resolved. Could you please check @supaplextw? I cannot see any differences in the labels for the various variants. Do you have an example?

**Comment by Supaplextw** [comment]
It doesn't work. I'll ask some friend and ask another Chinese Wikipedian folks for help. 

If it works, it should be the following:
https://zh.wikipedia.org/w/index.php?title=後龍車站

 'zh':  '後龍車站'
 'zh-hans': '後龙车站'
 'zh-hant': '後龍車站',
 'zh-cn': '後龙车站',
 'zh-hk': '後龍車站',
 'zh-mo': '後龍車站',
 'zh-sg': '後龙车站',
 'zh-tw': '後龍車站'

**Comment by dschwen** [comment]
Please try again. I made a trivial mistake that cause the automatic conversion not to be used. It looks like the labels are changing now.

**Comment by Supaplextw** [comment]
It seems to work. Thank you @dschwen for your hard work.

**Comment by dschwen** [comment]
@Supaplextw , if you want to post a notice about the variant support on zh.wp that'd be great. I just created https://commons.wikimedia.org/wiki/File:Wma_zh_variants.gif to illustrate the feature.

I'll open an issue for adjustable font size. It seems to me that 7pt is a tad too small for good readability of chinese characters.
